project:
  type: website

execute:
  freeze: auto

website:
  title: "ReadyResearchers Template"
  navbar:
    right:
      - thesis/index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: journal
    css: styles.css



