name: Related work review
description: Provide peer review feedback for the Related Work chapter of this thesis project.
title: "Fall 2024 Related Work Peer Review"
body:
  - type: markdown
    attributes:
      value: |
        Please respond to the following questions about the introduction chapter.
  - type: checkboxes
    attributes:
      label: Source cohesion
      description: After reading the the Related Work section, it's clear why the sources used were included.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: Source cohesion description
      description: Tell the author more about your thoughts on source cohesion. What didn't make sense?
  - type: checkboxes
    attributes:
      label: Source authority
      description: Sources used in this section are authoritative and appropriate to the project.
      options:
        - label: "Yes"
        - label: "No"
  - type: checkboxes
    attributes:
      label: Source quality
      description: Rank the level of source quality demonstrated by the sources used.
      options:
        - label: "High"
        - label: "Moderate"
        - label: "Low"
  - type: checkboxes
    attributes:
      label: Source presentation
      description: The author paid close attention to the order of sourcing to develop ideas from the literature.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: Source presentation description
      description: Provide a rough outline of the topics presented in the Related Work section.
  - type: checkboxes
    attributes:
      label: Source interactions, relationships
      description: The author discusses the relationships between sources of different categories or themes.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: Source interactions, relationships description
      description: Where would additional discussion occur? What source areas lack clear connection?
  - type: checkboxes
    attributes:
      label: Project ethics
      description: The author substantively discusses more than two (2) ethical issues that the project presents or addreses.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: Project ethics description
      description: What additional ethical areas did the author not include? What challenges need more definition?
  - type: checkboxes
    attributes:
      label: Project sourcing
      description: The author cites sources in the Related Work.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: General Related Work feedback
      description: "Highlight 3 areas (excluding grammar) that the author should develop further. Include: one minor, one moderate, and one major revision area."
