project:
  type: manuscript
  output-dir: _site/thesis
bibliography: references.bib
csl: journal-of-the-acm.csl
format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
