on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
